import {
  personCircleOutline,
  logOutOutline,
  homeOutline,
  addOutline,
  pencilOutline,
  trashOutline,
  person,
  flame,
  apps,
  logIn,
  reader,
  chatbox,
  chatbubbles,
  film,
  list,
  albums,
  logoWordpress,
  cog,
  gameController,
  card,
  nuclear,
  analytics,
  map,
  logoWhatsapp,
  partlySunny,
  star,
  moon,
  bulb,
  pizza,
  brush,
  water,
  briefcase,
  square,
  rose,
  remove,
  aperture,
  logoYoutube,
  grid,
  image,
  easel,
  menu,
  bonfire,
  images,
  funnel,
  logoInstagram,
  sunny,
  phoneLandscape,
  document,
  school,
  heart,
  globe,
  alert,
  infinite,
  refresh,
  logoIonic,
  code,
  radioButtonOff,
  refreshCircle,
  calendar,
  fileTrayFullSharp,
} from 'ionicons/icons';
import { addIcons } from 'ionicons';

export function provideAppIcons() {
  addIcons({
    'person-circle-outline': personCircleOutline,
    'log-out-outline': logOutOutline,
    'home-outline': homeOutline,
    'add-outline': addOutline,
    'pencil-outline': pencilOutline,
    'trash-outline': trashOutline,
    person: person,
    flame: flame,
    apps: apps,
    'log-in': logIn,
    reader: reader,
    chatbox: chatbox,
    chatbubbles: chatbubbles,
    film: film,
    list: list,
    albums: albums,
    'logo-wordpress': logoWordpress,
    cog: cog,
    'game-controller': gameController,
    card: card,
    nuclear: nuclear,
    analytics: analytics,
    map: map,
    'partly-sunny': partlySunny,
    star: star,
    moon: moon,
    bulb: bulb,
    pizza: pizza,
    brush: brush,
    water: water,
    briefcase: briefcase,
    square: square,
    rose: rose,
    remove: remove,
    aperture: aperture,
    grid: grid,
    image: image,
    easel: easel,
    menu: menu,
    bonfire: bonfire,
    funnel: funnel,
    images: images,
    sunny: sunny,
    'phone-landscape': phoneLandscape,
    document: document,
    school: school,
    heart: heart,
    alert: alert,
    globe: globe,
    infinite: infinite,
    refresh: refresh,
    'logo-ionic': logoIonic,
    code: code,
    'radio-button-off': radioButtonOff,
    'refresh-circle': refreshCircle,
    calendar: calendar,
    'file-tray-full-sharp': fileTrayFullSharp,
    'logo-facebook': 'assets/socialShare/logo-facebook.svg',
    'logo-whatsapp': logoWhatsapp,
    'logo-instagram': logoInstagram,
    'logo-telegram': 'assets/socialShare/telegram.svg',
    'logo-tinder': 'assets/socialShare/tinder.svg',
    'logo-boo': 'assets/socialShare/boo.svg',
    'logo-youtube': logoYoutube,
    'logo-google': 'assets/icon/google.png',
    'apps-outline': 'assets/socialShare/apps-outline.svg',
    'call-outline': 'assets/socialShare/call-outline.svg',
  });
}
